# Do *not* load any libs here that are *not* part of Ruby’s standard-lib. Ever.

desc "Install all dependencies"
task :bootstrap do
  if system('which bundle')
    sh "bundle install"
    sh "git submodule update --init"
    # etc
  else
    $stderr.puts "\033[0;31m[!] Please install the bundler gem manually: $ [sudo] gem install bundler\e[0m"
    exit 1
  end
end

begin
  # Whatever lib you need to load that is *not* part of Ruby’s standard-lib,
  # this includes Bundler.
  
  require 'bundler/gem_tasks'
  require 'bundler/setup'

  task :something_that_depends_on_the_gem_bundle do
    # etc
  end

rescue LoadError
  $stderr.puts "\033[0;33m[!] Disabling rake tasks because the environment couldn’t be loaded. Be sure to run `rake bootstrap` first.\e[0m"
end